package:
  name: recast3d
  version: 1.0.0.rc.1

source:
  # path: ../
  git_url: https://github.com/ahendriksen/RECAST3D
  git_tag: conda-packaging

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-common') }}
    - {{ cdt('libx11-devel') }}
    - {{ cdt('xorg-x11-proto-devel') }}
    - {{ cdt('xorg-x11-server-common') }}
    - {{ cdt('xorg-x11-server-xvfb') }}
    - {{ cdt('xorg-x11-util-macros') }}
    - {{ cdt('xorg-x11-xauth') }}
    - {{ cdt('libxrandr-devel') }}
    - {{ cdt('libxinerama-devel') }}
    - {{ cdt('libxcursor-devel') }}
    - {{ cdt('libxau-devel') }}
    - {{ cdt('libdrm-devel') }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]

    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - pkg-config                # [unix]
    - cmake
    - make
  host:
    - boost
    - zeromq
    - eigen
    - pybind11
    - libxcb                             # [linux]
    - assimp
    - glfw
    # - glm                       # header only
  run:
    - zeromq
    - eigen
    - libxcb                             # [linux]
    - xorg-libxrandr         # [linux]
    - xorg-libxcursor        # [linux]
    - glfw
    - assimp

test:
  commands:
    # Verify git location.
    - test -f $PREFIX/bin/recast3d       # [unix]


about:
  home: https://github.com/cicwi/RECAST3D
  license: GPLv3
  summary: 'RECAST3D: the all-seeing eye'
